import React from 'react'
import './contact.css'

const Contact = () => {
    return (
        <div>
            <h1 className='contacth1'>Contact Us.</h1>
            <hr />
            <h4 className='contactlorem'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod asperiores autem maxime molestiae totam dolor quo nobis repellendus quaerat nam qui non accusamus, nihil consequatur minima dolorem praesentium quisquam optio eos, quas officiis unde ab assumenda voluptates? Numquam saepe neque repellat praesentium? Possimus enim architecto et cumque placeat unde, repellat libero illo? Dicta corrupti labore esse quidem nemo sint cupiditate, distinctio totam ab officiis aperiam ex vero obcaecati voluptatum illo molestias pariatur quos fugit expedita aut. Officiis beatae magni ducimus ipsum sit nostrum voluptate est nihil suscipit ratione voluptas, nulla eveniet in atque vero labore, ab praesentium aut? Quibusdam voluptatum soluta maiores veniam voluptatem aliquid nulla ea ab eius, debitis ipsa sit fugiat. Repellendus illo ad sit perferendis iure id temporibus accusantium, quo deleniti cupiditate facilis optio quaerat eligendi, vitae laborum commodi recusandae, tenetur aliquid hic omnis nisi. Aspernatur laborum facilis, vel soluta labore culpa? Aspernatur quasi dignissimos corrupti repudiandae. Dignissimos vitae nesciunt eos culpa quo, suscipit facilis cupiditate temporibus sunt perspiciatis velit debitis alias. Totam hic, repellendus sequi incidunt quas veritatis eligendi officia natus assumenda nemo, ratione repellat praesentium, recusandae odit suscipit minima aperiam delectus non inventore doloribus? Itaque et quisquam, reprehenderit sint a dolorem. Cumque earum hic, eligendi mollitia error nostrum, autem itaque quasi quisquam modi explicabo porro aliquam nulla tempore officiis dolorum exercitationem deleniti, voluptates ipsa natus vitae vero laborum quo! Suscipit enim corrupti itaque nostrum quasi, quia praesentium minus debitis qui eos esse, explicabo pariatur, maiores nihil velit? Officiis omnis ratione est ea animi, ut repudiandae!</h4><br />
            <h4 className='contactlorem'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis quo dolore dignissimos hic natus sequi quam placeat possimus ad porro labore dicta beatae suscipit, accusamus rerum ullam corporis facere impedit rem nostrum iusto sint! Repellendus veritatis ad blanditiis ipsum aperiam, nam, laborum in facilis excepturi enim delectus tenetur incidunt corporis totam architecto quis rerum, nostrum eveniet voluptas. Accusantium deleniti esse in tempora, perferendis sit voluptate provident. Nulla porro laborum rerum, adipisci excepturi ullam provident amet inventore eveniet autem totam placeat temporibus velit voluptate labore expedita et, repellendus quasi sequi at culpa quia? Voluptatibus minima voluptate eos, incidunt asperiores perferendis. Delectus illo assumenda ullam pariatur id veritatis adipisci veniam vero consequatur, a libero doloremque, doloribus magnam distinctio harum repellat laborum debitis velit mollitia porro dolorum aspernatur. Placeat sunt ut quos neque unde iusto minima culpa fugiat quia ipsam deleniti ea quod quidem voluptatem beatae dolores odit saepe, assumenda obcaecati cumque commodi?</h4><br />
            
        </div>
    )
}

export default Contact
